### ISSUE TITLE
Maven Install Failure on Windows

### ISSUE THREAD

**Issue by MTWebSer** [robinhowlett/chart-parser#2]
Hey Robin, 

Very nice project, thanks for sharing with the community. I came across this bug on Windows where the maven install fails at the footnote and csv tests. There seems to be a disconnect where the Windows' instance of the program isn't properly processing the carriage return within the parsed data and the hard coded string in the test doesn't include the \r character. 

EXPECTED:
...CANDY SWEETHEART closed well midstretch for place. MIDNIGHTWITHDRAWAL was well back early and...

FOUND: 
...CANDY SWEETHEART closed well midstretch for place.\r MIDNIGHTWITHDRAWAL was well back early and...

Sorry, I know nothing about Java or else I would try to be more helpful. Hoping to use this project as a start to learning more though. 

Keep up the good work!
-Mike

**Comment by robinhowlett** [comment]
This should be resolved, yes.
