### ISSUE TITLE
Will this work with my horse racing tips site?

### ISSUE THREAD

**Issue by sion10** [robinhowlett/chart-parser#3]
Hi
I have a horse racing tipster service at [https://www.startipster.com](https://www.startipster.com) and i was wondering if there would be any way to implement this. Id really like to include horse racing results and trying to figure out the best ways to achieve this.
Thanks

**Comment by robinhowlett** [comment]
I imagine if the company that produces these PDFs found out you were distributing the data on your commercial website, they would have their lawyers on you pretty quickly.
