### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by greyarea23** [robinhowlett/chart-parser#5]
When running the maven install, I'm faced with 1 test failure of the 192 test runs: 

Failed tests:  convertToCsv_WithSamplePdfChart_CreatesListOfCsvs(com.robinhowlett.chartparser.ChartParserTest): (..)

Any advice?

**Comment by robinhowlett** [comment]
Are you developing on Windows? Have you pulled the latest changes? If not, I made a change about a week ago to that may be what you are experiencing: https://github.com/robinhowlett/chart-parser/commit/d3100af33008a79ac5f6ad40b0bec15ef386cf34#diff-6b1dddb3627d19e518bf67a9be56a057

**Comment by robinhowlett** [comment]
@greyarea23 any luck?

**Comment by greyarea23** [comment]
Yes, Eclipse on Windows. And it looks like the latest changes have been pulled. For what it's worth, the install succeeds when deleting the related convertToCsv test

**Comment by robinhowlett** [comment]
OK i installed Eclipse on Windows, but actually other tests failed. However I think I know what it is (how the matchers are treating unexpected carriage returns). I'll try to fix soon but I won't have a Windows machine until next week to test.

In the meantime, if you are running via Maven adding `-DskipTests` will ensure the tests are not run.

**Comment by greyarea23** [comment]
Great, thanks for the help

**Comment by robinhowlett** [comment]
@greyarea23 can you checkout [the `5_line-separator-wagering` branch](https://github.com/robinhowlett/chart-parser/compare/5_line-separator-wagering) please and try building again. 

I still can't get the `convertToCsv_WithSamplePdfChart_CreatesListOfCsvs` to fail on Eclipse + Windows but I did find a line separator-related bug with `com.robinhowlett.chartparser.charts.pdf.wagering.WagerPayoffPoolsTest.ExoticPayoffPoolTest.WinningNumbersPayoffTest` and `com.robinhowlett.chartparser.charts.pdf.wagering.WagerPayoffPoolsTest.ExoticPayoffPoolTest.WagerNameUnitTest`.

If it still fails, I'd like to help you debug.

**Comment by robinhowlett** [comment]
I've merged this to `master` already. Will close by the weekend if there are no further responses.
